name: quak
channels:
  - conda-forge
dependencies:
  - python=3.9
  - tensorflow=2.12.0
  - gwpy
  - astropy
  # frame file I/O dependencies
  - python-ldas-tools-framecpp
  - python-nds2-client
  # omicron dependencies
  - python-ligo-lw
  - pyomicron
  - omicron>=4.0.0
  - dqsegdb2
  - uproot
  # injection dependencies
  - bilby<1.2
  - lalsuite