[tool.poetry]
name = "gwak"
version = "0.1.0"
description = "Best AD ever"
authors = ["Katya Govorkova <katyag@mit.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
